name: 'dsci532'
channels:
  - conda-forge
dependencies:
  - ipykernel
  - ipyleaflet
  - matplotlib
  - nbformat
  - numpy
  - pandas
  - pip
  - plotly
  - python=3.12
  - scienceplots
  - scikit-learn
  - seaborn
  - pip:
    - shiny
    - shinywidgets